# Config file for Air
root = "."

[build]
  # Binary file air builds
  bin = "tmp/main"
  # Command to build the main binary
  cmd = "go build -o tmp/main ."
  # Custom go binary path
  # full_bin = "path/to/custom/go"
  # Working directory
  # work_dir = "."
  # Directory that contains the main package
  src_dir = "."
  # Extensions to watch
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Ignore these directories or files
  exclude_dir = ["assets", "tmp", "vendor"]
  # Ignore files with specific names
  exclude_file = []
  # Exclude specific files by regular expression
  exclude_regex = ["_test\\.go"]
  send_interrupt = false
  stop_on_error = true


[log]
  # Show log time
  time = true

[serve]
  # Command to serve
  cmd = "./tmp/main serve"
  # Custom env variables
  # envs = ["AIR_ENV=dev"]
  # Port to serve
  port = 3000

# Miscellaneous configurations
[color]
  main = "cyan"
  watcher = "yellow"
  building = "green"
  serving = "magenta"
  reloading = "blue"
  err = "red"

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false